### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by AnthyG** [AnthyG/Thundote#1]
### Main Points
- [ ] Private notes
- [ ] Note-Sharing
- [ ] Options
- [ ] Markdown-Support
- [x] Note-Sorting

-------

#### Private notes
- [x] Auto-encrypt (Encrypts with users public-key using ECIES)
- [ ] Manual-encrypt (Encrypts with custom AES-Inputs and optionally ECIES)

#### Note-Sharing
- ?!read-only?! (maybe a clone-function could be added)
- to:
- - cert-user-name/ public-key (encrypt with other users public-key using ECIES)
- - All ~~(Encrypts with users public-key, using AES)~~ (Encrypts with custom AES-Inputs)

#### Options
- [ ] Auto-save (refers to _Private Notes > Auto-encrypt_)
- [ ] Day-mode (not night-mode, because [AnthyG/spectre-dark2](/AnthyG/spectre-dark2))

#### Markdown-Support
Quite obvious what it does,.. right!?

**Comment by ghost** [comment]
> Are you planning on allowing people to drag notes? I think that would be a cool feature to sort notes. Also, pinning could be useful too. And maybe reminders where the note shows in a reminder section when the date/time has passed for that note.

**Comment by AnthyG** [comment]
I probably have to re-write the stuff at the top, because it doesn't quite fit anymore with what I have on my hand-written list..

**Comment by AnthyG** [comment]
I've added the very basic stuff for reminders with commit 257893f2f0b32f18cc1e125bdad59e5b0901cce3 and added the ability to drag and drop notes with commit 2219dddb547da5444ecdb1173401056961de5e57.
But as I'm not quite sure yet, on what I need to do, so that the list gets saved correctly, the new order of notes doesn't get saved as of now.

**Comment by AnthyG** [comment]
I added the function to save the order of notes after dragging, and fixed the edit-function with commit cc6a8bb80811f7ad9c8395c0e1d0d5e6566e2ced (on the [New-DB-Design-because-of-I-dunno Branch](https://github.com/AnthyG/Thundote/tree/New-DB-Design-because-of-I-dunno))
